# Welcome {.unnumbered}

Welcome to R for Clinical Study Reports and Submission.
Clinical study reports (CSR) are crucial components in clinical trial development.
A CSR is an "integrated" full scientific report of an individual clinical trials.

The [ICH E3: Structure and Content of Clinical Study Reports](https://database.ich.org/sites/default/files/E3_Guideline.pdf)
offers comprehensive instructions to sponsors on the creation of a CSR.
This book is a clear and straightforward guide on using R to streamline the
process of preparing CSRs. Additionally, it provides detailed guidance on the
submission process to regulatory agencies. Whether you are a beginner or an
experienced R programmer, this book is an indispensable asset in your
clinical reporting toolkit.

**This is a work-in-progress draft.**

::: {.content-visible when-format="html"}

## Events {.unnumbered}

```{css, echo=FALSE}
.table {
  font-size: 0.825rem;
}
```

```{r, echo=FALSE}
knitr::kable(
  read.table("events.tsv",
    stringsAsFactors = FALSE,
    header = TRUE,
    sep = "\t"
  )
)
```

:::
