# Introduction {#intro}

## Folder structure 

In clinical trial development, developers need to organize source code to deliver 
Study Data Tabulation Model (SDTM) or Analysis Dataset Model (ADaM) datasets 
and tables, listings, and figures (TLFs).
For example, a Phase 3 clinical trial typically consists hundreds of TLFs. 
A consistent and well-defined folder structure is crucial 
to managing a clinical trial analysis and reporting (A&R) project. 

We recommend using R package folder structure to organize all the A&R related 
source code and documentation for a clinical trial A&R project. 
By using the R package folder structure, 
you can follow the convention to organize your code as other contributors on CRAN.
This consistent approach simplifies the communication for all developers 
within and across organizations. 

- For a new R developer, 
it is an essential step to develop R packages 
when you want to share your work with others. 
You will learn one folder structure that is widely used 
in the R community with outstanding tutorials and tools for free. 

- For an experienced R developer, there is a minimal learning curve.

- For an organization, it simplifies the process, tool, template, 
and training development, because a unified folder structure is used 
to develop and maintain standard tool and analysis projects.  

The workflow around an R package can also improve 
the tractability and reproducibility for an analysis project [@marwick2018packaging].

In addition, R package folder structure is also recommended 
to develop Shiny app as discussed 
in [Chapter 20 of Master Shiny](https://mastering-shiny.org/scaling-packaging.html) book 
and [Engineering Production-Grade Shiny Apps](https://engineering-shiny.org/golem.html) book.   

## In this book

This book is an intermediate-level book by 
assuming readers have R programming and clinical development knowledge.
The assumption of each part is as below:

- Part 1, "Delivering TLFs in CSR" provides general information with examples 
to create tables, listings, and figures. 
In this part, we assume readers are individual contributors to a clinical project
with some experience in R programming. 
We expect readers are familiar with data manipulation in R. 
Some good reference includes [Hands-On Programming with R](https://rstudio-education.github.io/hopr/),
[R for Data Science](https://r4ds.had.co.nz/) and 
[Data Manipulation with R](https://www.amazon.com/Data-Manipulation-R-Use/dp/0387747303).

- Part 2, "Clinical Trial Project" provides general information 
with examples to manage a clinical trial A&R project. 
In this part, we assume a reader is a project lead with experience in R package development. 
Some good reference includes [R packages](https://r-pkgs.org/) and 
[The tidyverse style guide](https://style.tidyverse.org/). 

- Part 3, "eCTD Submission package"
provides general information in preparing 
submission package related to clinical study report (CSR) in 
electronic Common Technical Document (eCTD). 
In this part, we assume a reader is a project lead of a clinical project 
with experience in R package development as well.     

## Philosophy 

We share the same philosophy described in 
[Section 1.1 of R Packages book](https://r-pkgs.org/intro.html?q=Marwick#intro-phil) 
and quote here.

- "Anything that can be automated, should be automated." 
- "Do as little as possible by hand. Do as much as possible with functions." 
- "The goal is to spend your time thinking about what you want to do 
rather than thinking about the minutiae of the package structure."
