# Project Management {#manage}

For A&R deliverables in a clinical project development, 
a clearly defined process or system development lifecycle (SDLC) 
is crucial to ensure regulatory compliant. 

SDLC for A&R deliverables can be defined in stages: 

- planning: a planning stage to define the scope of a project.  
- development: a development stage to implement target deliverables. 
- validation: a validation stage to verify target deliverables. 
- operation: an operation stage to deliver work to stakeholders. 

The define stage is an important stage in the SDLC lifecycle 
as the requirements for all A&R deliverables are gathered and documented. 

Importantly, we should not consider SDLC as a linear process. 
For example, if study team identify new requirement in a development or validation stage, 
team shall return to planning stage to discuss and align the scope. 
An [agile project management](https://www.atlassian.com/agile/project-management) approach is suitable 
and recommended to an A&R clinical development project.
The goal is to embrace an iterative approach that continue improve target deliverables based on
frequent customer feedback. 

There are many good tools to implement agile project management strategy, for example:

- [github project board](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards)
- [Jira](https://www.atlassian.com/software/jira)

## Planning 

In the planning stage, a project leader shall identifies all the deliverables, 
e.g. a list of table, listing, and figures (TLFs). 
For each TLFs, team shall prepare necessary specifications: 

- mock-up
- validation level (e.g. independent review or double programming)
- etc.

ToDo: add a simplified mock-up and A&R grid. 

project leader shall also align work assignment with team members.
The purpose is to answer the question on "who is doing what?". 

ToDo: add a simplified validation tracker 

Project lead shall also setup a project folder as discussed in Chapter \@ref(folder).
The project initiation can be simplified by creating an 
[RStudio project template](https://rstudio.github.io/rstudio-extensions/rstudio_project_templates.html).  

To enable reproducibility, project leader shall also review the startup file 
(i.e. `.Rprofile` discussed in Section \@ref(manage)) and define:

- R version 
- Repository of R packages with a snapshot date 
- Project package library path 
- etc. 

> After project initiate, modifying `.Rprofile` will be a risk of reproducibility 
> and shall be handled carefully if necessary. 

## Development 

After a project is initiated, the study team start to develop TLFs based on 
pre-defined mock-up tables assigned to each team member. 

The analysis code and relevant description can be saved in R markdown files 
in the `vignettes` folder. 
The use of R markdown allow developer to assemble narrative text, code and its
comments in one place to simplify documentation. 
It would be helpful to define a name convention for all TLFs deliverables. 
For example, we can use `tlf_` prefix in the filename to indicate that the Rmarkdown is to deliver TLFs. 
For example, `tlf_001_ds.Rmd` is an Rmarkdown file for disposition table. 
Multiple TLFs with similar design can be included in one Rmarkdown file. 

ToDo: add a file path for `esubdemo`

To validate the results, 
developer shall also save the last dataset before creating TLFs in RTF format to `.Rdata` files. 

## Validation 

## Operation 






