# (PART) Delivering TLFs in CSR {-}

# Overview

## Background

In clinical trial development, it is a critical step to submit information on medicinal products to regulatory agencies. [Electronic Common Technical Document (eCTD)](https://en.wikipedia.org/wiki/Electronic_common_technical_document) 
has become a worldwide regulatory submission standard format. 
For example, [the United States Food and Drug Administration (US FDA) required new drug applications, biologics license applications must be submitted using eCTD format](https://www.fda.gov/drugs/electronic-regulatory-submission-and-review/electronic-common-technical-document-ectd). Clinical Data Interchange Standards Consortium (CDISC) provided a 
[pilot project
following ICH E3 guidance](https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse).
(??? What is the correlation between CDISC and eCTD? Are they to standard format of CSR? Besides, as a beginner, I feel it is better to explain "pilot project" in details.)

Within eCTD, clinical study reports (CSR) are located at module 5. 
[ICH E3 guidance](https://www.ich.org/page/efficacy-guidelines) provide 
compilation of structure and content of clinical study reports.

A typical CSR contain full details of an individual clinical study 
including clinical and statistical description, presentations, and analyses. 
A large number of tables and figures are incorporated into the main text and appendices 
of a CSR. In CDISC pilot project, an [example CSR](https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/53-clin-stud-rep/535-rep-effic-safety-stud/5351-stud-rep-contr/cdiscpilot01/cdiscpilot01.pdf) 
is also provided. If you are interested in more examples of clinical study reports, 
the European Medicines Agency (EMA) publishes clinical data including 
clinical study reports submitted by pharmaceutical companies 
on [EMA clincal data website](https://clinicaldata.ema.europa.eu/web/cdp/home).  

Building CSR is a team work with clinicians, medical writers, statisticians and statistical programmers.
Here, we focus on the work and deliverables completed by statisticians and statistical programmers. 
In an organization, A group of statisticians and statistical programmers commonly work together to 
define, develop, validate and deliver tables, listings and figures (TLFs) required for a CSR.
Microsoft Word is widely used to prepare CSR in pharmaceutical industry. 
Therefore, `rtf`, `doc`, `docx` are commonly used format to deliver TLFs. 

In this chapter, our focus is to illustrate how to create tables, listings and figures (TLFs) in RTF format 
that is commonly used in a CSR. The examples are in compliance of 
[FDA's Portable Document Format (PDF) Specifications](https://www.fda.gov/media/76797/download)

> FDA's PDF specification is a general reference, each organization may define 
> more specific TLF format requirement that can be different from the examples in this book. 

These TLFs are typically used to summarize efficacy and safety statistical analysis results of a drug (or treatment).  

## Structure and Content

In the rest of this chapter, we are following the [ICH E3 guidance](https://www.ich.org/page/efficacy-guidelines) on 
structure and content of clinical study reports. 

In a CSR, most of TLFs are located in 

- Section 10: Study patients 
- Section 11: Efficacy evaluation
- Section 12: Safety evaluation 
- Section 14: Tables, Figures and Graphs referred to but not included in the text
- Section 16: Appendices

## Datasets

We used public available CDISC pilot [study data located at CDISC Bitbucket repository](https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/analysis/adam/datasets).

For simplicity, we have downloaded all these datasets into `adam_data` folder of 
this project and transfer them from `.xpt` format to `sas7bdat` format. 

The dataset structure is following [CDISC Analysis Data Model (ADaM)](https://www.cdisc.org/standards/foundational/adam). 

