rmarkdown::render("slides/workshop-slides.Rmd")
rmarkdown::render("slides/china-r.Rmd")
rmarkdown::render("slides/r4csr-gwu.Rmd")
rmarkdown::render("slides/r4csr-rstudio.Rmd")
rmarkdown::render("slides/fda-workshop-slides.Rmd")
rmarkdown::render("slides/r4csr-psi.Rmd")
